# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure(2) do |config|
  config.vm.box = "ubuntu/trusty64"

  #config.vm.network "public_network", ip: "192.168.0.240"
  config.vm.network "private_network", ip: "192.168.33.100"
  config.vm.hostname = "tomcat"

   config.vm.provider "virtualbox" do |vb|
    vb.memory = "1024"
   end
   config.vm.provision "shell", inline: <<-SHELL
     sudo wget http://apt.puppetlabs.com/puppetlabs-release-trusty.deb 
     sudo dpkg -i puppetlabs-release-trusty.deb 
     sudo apt-get update -y  
     sudo apt-get install puppet -y
   SHELL
  config.vm.provision "puppet" do |puppet|
    puppet.manifests_path = "manifests"
    puppet.manifest_file = "default.pp"
    puppet.module_path = "modules"
    puppet.hiera_config_path = "hiera.yaml"
    puppet.options = "--verbose --debug"
  end
end
